[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
cache_path  = 'forge-cache'

remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@solidity-parser/=node_modules/truffle-flattener/node_modules/@solidity-parser/',
    '@uniswap/=node_modules/@uniswap/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]

[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
fuji = "https://api.avax-test.network/ext/bc/C/rpc"
arbitrum = "https://arb1.arbitrum.io/rpc"
bsc = "https://bscrpc.com"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}", chain = 42161 }
avalanche = { key = "${SNOWTRACE_API_KEY}", chain = 43114 }
arbitrum_goerli = { key = "${ARBISCAN_API_KEY}", chain = 421613 }
fuji = { key = "${SNOWTRACE_API_KEY}", chain = 43113 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config